source: .
destination: ./_site
plugins: ./_plugins
layout: ./_layout

source: .
source: .
source: .
destination: ./_site
plugins: ./_plugins
layout: ./_layout

permalink: /:title

destination: ./_site
plugins: ./_plugins
layout: ./_layout

permalink: /:title

destination: ./_site
plugins: ./_plugins
layout: ./_layout

permalink: /:title

permalink: /:title

